export const AUTH_LOG_OUT = 'AUTH_LOG_OUT'
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'


export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const DONE_TASK = 'DONE_TASK'

export const INIT_MODULES = 'INIT_MODULES'
export const ADD_PROJECT_START = 'ADD_PROJECT_START'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAIL  = 'ADD_PROJECT_FAIL'
export const CLEAR_ERROR ='CLEAR_ERROR'
export const EDIT_PROJECT ='EDIT_PROJECT'


export const INIT_TASKS = 'INIT_TASKS'
export const INIT_PROJECTS = 'INIT_PROJECTS'


export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE'
export const ADD_EMPLOYEE_START = 'ADD_EMPLOYEE_START'
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS'
export const ADD_EMPLOYEE_FAIL = 'ADD_EMPLOYEE_FAIL'
export const INIT_EMPLOYEES = 'INIT_EMPLOYEES'


